### ISSUE TITLE
Discourage usage of consecutive maps and filters in threading macros

### ISSUE THREAD

**Issue by andreyorst** [borkdude/clj-kondo#1008] opened 2020-09-11 17:53 UTC
I often see the pattern llike 
```clojure
(->> col
     (map f)
     (filter p)
     (map f1)
     ,,,)
```
while being  easy to understand this is quite expensive in terms of intermediate collections produced by maps and filters. Clojure has transducers for this specific case and this code should be rewritten as

```clojure
(sequence (comp (map f)
                (filter p)
                (map f1)
                ,,,)
          col)
```

Which does the same thing and has better performance, but I rarely see transducer usage, as it seems that it's unpopular feature often over-thought as a complex one for some reason, which is a shame, as this thing is both powerful, performant and functional.

I think that clj-kondo could discourage usage of this threading pattern and produce a warning when there is too many consecutive maps and filters (and possibly other forms that can return transducer) are stacked together, so I've wrote this hook:

```clojure
(ns hooks.thread-macros
  (:require [clj-kondo.hooks-api :as api]))

(def consecutive-threshold 2)
(def transduceable #{'map
                     'filter})

(defn consecutive-threading [{:keys [:node]}]
  (let [[_ & forms] (rest (:children node))]
    (loop [forms forms
           counter 0]
      (when-let [form (first forms)]
        (if (contains? transduceable (some-> form :children first api/sexpr))
          (if (>= counter consecutive-threshold)
            (api/reg-finding!
             (assoc (meta node)
                    :message "prefer transducers to consecutive maps or filters in threading macros"
                    :type :expensive-threading))
            (recur (next forms)
                   (inc counter)))
          (recur (next forms)
                 0))))))
```

It walks the tree of `->>` macro and counts sequential calls to `transduceable` functions, and reports if more than 2 were found. Although not every form of threading can be turned into equivalent transducer composition, but I've never seen this hook triggering on such patterns.

What are your thoughts on if clj-kondo should do this by default, or maybe this should instead go into [config](https://github.com/clj-kondo/config) repo? Or maybe this is premature optimization and it should be avoided completely. Thanks!

**Comment by borkdude** [comment] 2020-09-11 18:01
I think this is a duplicate of #323

**Comment by andreyorst** [comment] 2020-09-11 18:11
Oh, I've couldn't find it by searching `threading`, should've used `transducers` instead, sorry. Yeah, this seems as duplicate, although I'm not suggesting that clj-kondo should provide example of how rewriting the code, as it seems quite complicated task, and if this could have been done automatically, Clojure compiler should do it for us for any threading form, but it doesn't and I doubt that this is even possible.

Regarding the point of lazy collections performance -- yes, transducer may be not as performant, but it depends if we really want laziness or just forgot about it, so a hint from clj-kondo still would be nice. Maybe warning should be reworded to something like `"prefer transducers to consecutive maps or filters unless you want lazy collection"`.

Should I move this to comment section under #323 and close this?

**Comment by borkdude** [comment] 2020-09-11 18:13
Yes, close + move/copy comments seems good to me.

**Closed** 2020-09-11 18:21 UTC
