### ISSUE TITLE
False positive with clojure.string/replace

### ISSUE THREAD

**Issue by tanzoniteblack** [borkdude/clj-kondo#795] opened 2020-03-10 21:08 UTC
```clojure
(require '[clojure.string :as str])
(str/replace " " #" " {" " "-"})
```

```
example.clj:3:23: error: Regex match arg requires string or function replacement arg.
```

Hash-maps are valid functions, and work just fine with `str/replace`, but clj-kondo reports this as an error anyways.

**Comment by borkdude** [comment] 2020-03-10 21:10
Duplicate of #787.

**Closed** 2020-03-20 10:29 UTC
Labels: false positive, next-release
