### ISSUE TITLE
Support clojure 1.9 on the JVM

### ISSUE THREAD

**Issue by l3nz** [borkdude/clj-kondo#305] opened 2019-06-28 15:06 UTC
**version**

Latest - 2019.06.23-alpha

**platform**

JVM  - clj 1.9
```

:dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/spec.alpha "0.1.143"]
                 [expound "0.7.2"]
                 [clj-http "3.9.1"]
                 [clash "1.3.2"]
                 [cheshire "5.7.0"]
                 ;[clojure-future-spec "1.9.0-alpha15"]
                 [org.clojure/test.check "0.9.0"]
                 ;[org.apache.httpcomponents/httpclient "4.5.3"]

                 [lenz/capacitor "0.6.0.2"]
                 [cli-matic "0.3.6"]
                 [say-cheez "0.1.1"]

                 [clj-kondo "2019.06.23-alpha" :scope "provided"]]
```

**problem**

It looks like Kondo crashes on a (working) "spec/def" call; and when it crashes, it does not print the correct line number.

**repro**

```
(ns l2i.kondo-boom
  (:require [clash.core :as clash]
            [cheshire.core :as json]
            [clojure.spec.alpha :as s]
    ; [clojure.spec.test :as stest]
            )
  (:import [java.security MessageDigest]
           [java.io       BufferedReader
                          RandomAccessFile
                          FileDescriptor
                          FileReader
                          File]))


(s/def ::action string?)

```

It crashes with:

`src/l2i/kondo_boom.clj:0:0: error: can't parse src/l2i/kondo_boom.clj, clojure.lang.Keyword cannot be cast to java.lang.String`

If I remove the `(s/def...)` it does not complain.

**Comment by borkdude** [comment] 2019-06-28 15:13
@l3nz Since I can't reproduce this with the binary, this could be because another dependency interferes with clj-kondo. As I already expected this would happen, I started inlining rewrite-clj and tools.reader for the next release. This is already on master and as a SNAPSHOT on clojars:

https://clojars.org/clj-kondo/versions/2019.06.24-alpha-SNAPSHOT

Could you give that a try?

**Comment by l3nz** [comment] 2019-06-28 15:16
It doesn't:


```
Retrieving clj-kondo/clj-kondo/2019.06.24-alpha-SNAPSHOT/clj-kondo-2019.06.24-alpha-20190628.102038-9.pom from clojars
Retrieving org/clojure/clojure/1.10.1/clojure-1.10.1.pom from central
Retrieving clj-kondo/clj-kondo/2019.06.24-alpha-SNAPSHOT/clj-kondo-2019.06.24-alpha-20190628.102038-9.jar from clojars
src/l2i/cfg.clj:5:23: info: unresolved symbol BUILD
src/l2i/kondo_boom.clj:0:0: error: can't parse src/l2i/kondo_boom.clj, clojure.lang.Keyword cannot be cast to java.lang.String

```

**Comment by borkdude** [comment] 2019-06-28 15:21
@l3nz Is this code public somewhere?

**Comment by l3nz** [comment] 2019-06-28 15:30
> @l3nz Is this code public somewhere?

Yes: https://github.com/l3nz/kondo-issue

**Comment by borkdude** [comment] 2019-06-28 17:11
@l3nz I'm not sure yet why, but upgrading Clojure to 1.10.0 or 1.10.1 gave the right results.

**Comment by borkdude** [comment] 2019-06-28 17:15
@l3nz I found the issue:

```
(symbol :foo)
```
is only possible from clojure >= 1.10.0 and this is what's used in the code.

**Comment by borkdude** [comment] 2019-06-28 18:24
I'll rewrite any conversions from keywords to symbols to be compatible with Clojure 1.9 on the JVM.

**Comment by l3nz** [comment] 2019-06-29 07:19
Actually I was able to make it work in Leiningen:

```
  :aliases {
            "clj-kondo" ["with-profile" "kondo"
                         "trampoline" "run" "-m"
                         "clj-kondo.main" "--" "--lint" "src/" "--cache" ".cli-kondo-cache"]}

  :profiles {:kondo
             {:dependencies [[org.clojure/clojure "1.10.1"]
                             [clj-kondo "2019.06.23-alpha"]]}}

```

So I just type `lein clj-kondo` and it works

**Comment by borkdude** [comment] 2019-06-29 14:40
Fixed with https://github.com/borkdude/clj-kondo/commit/31b06289d099c5c189003dcc70ccda0db46e44ea

**Closed** 2019-06-29 16:19 UTC
Labels: enhancement, next-release
