### ISSUE TITLE
Warn for try form without catch or finally

### ISSUE THREAD

**Issue by didibus** [borkdude/clj-kondo#817] opened 2020-03-23 22:14 UTC
One thing that Joker warns against but not clj-kondo it seems are `try` forms without the presence of a `catch` or `finally` block:

```
(try (can-throw))
```

As far as I know, there are no reasons to ever want to do this. So I think having a warn for it would make sense.

**Comment by borkdude** [comment] 2020-03-23 22:22
Duplicate of #773.

**Closed by borkdude** 2020-03-23 22:22 UTC
