### ISSUE TITLE
Global Configuration

### ISSUE THREAD

**Issue by rschmukler** [borkdude/clj-kondo#790] opened 2020-03-09 16:43 UTC
**Is your feature request related to a problem? Please describe.**

Many Clojure programmers end up having a consistent set of libraries that they like to use. Having to duplicate `.clj-kondo/config.edn` across many projects can feel tedious at times.

**Describe the solution you'd like**
Similar to `deps.edn`, I'd like to propose that clj-kondo check `$HOME/.config/clj-kondo/config.edn` for a config and then merge it with overrides from `$PROJECT_ROOT/.clj-kondo/config.edn`.

**Describe alternatives you've considered**
It's fair to say that the explicit configuration is better and that this feature shouldn't exist, so that all contributors in a project have the same linting experience. That being said, I think the consistency can be enforced by having the project local overwrite the global.

I'm willing to implement this PR if it would be accepted.

**Comment by borkdude** [comment] 2020-03-09 16:49
Duplicate of #736.

**Closed by borkdude** 2020-03-09 16:49 UTC

**Comment by rschmukler** [comment] 2020-03-09 16:52
Sorry I missed it! Searched for global and missed it. Thanks for the quick reply.

**Comment by borkdude** [comment] 2020-03-09 16:52
No problem!
