### ISSUE TITLE
Feature request: Multi-threaded support

### ISSUE THREAD

**Issue by Heliosmaster** [borkdude/clj-kondo#807] opened 2020-03-16 15:02 UTC
Linting currently only takes up to 100% of a single CPU in my system.

Linting a large project we have takes almost a full minute. I'd like for more of my cores to be used to reduce that.

**Comment by borkdude** [comment] 2020-03-16 15:05
Hi @Heliosmaster. This is a duplicate of #632. There is a branch called `pmap`. It works for normal files and directories, but there is an issue with linting classpaths / jar-files. Welcome to help me investigate what is the issue here. What I basically did is replace mapcat with into + cat + pmap.

**Closed by borkdude** 2020-03-16 15:05 UTC

**Comment by Heliosmaster** [comment] 2020-03-16 15:23
Hi @borkdude. Thank you for your answer, apparently it did not occur to me to look for the keyword 'parallel' when looking for a duplicate 🤦‍♂ . Thanks for letting me know, I was also thinking that a `pmap` might do the job. Let's investigate and continue on the other issue :)
